apiVersion: apps/v1

kind: Deployment

metadata:

  labels:

    app: techtrends

  name: techtrends

  namespace: sandbox

spec:

  replicas:  {{ .Values.replicaCount }}

  selector:

    matchLabels:

      app: techtrends

  template:

    metadata:

      labels:

        app: techtrends

    spec:

      containers:

      - image: richardvecsey/techtrends:latest

        name: techtrends

        ports:

          - containerPort: 3111

            protocol: TCP

        livenessProbe:

          httpGet:

            path: {{ .Values.livenessProbe.path }}

            port: {{ .Values.livenessProbe.port }}

          initialDelaySeconds: 30

          periodSeconds: 3

        readinessProbe:

          httpGet:

            path: {{ .Values.readinessProbe.path }}

            port: {{ .Values.readinessProbe.port }}

          initialDelaySeconds: 30

          periodSeconds: 3

        resources:

          requests:

            memory: "64Mi"

            cpu: "250m"

          limits:

            memory: "128Mi"

            cpu: "500m"
