apiVersion: {{ .Values.apiVersion.short }}

kind: {{ .Values.kind.forservice }}

metadata:

  name: {{ .Values.metadata.name }}

  namespace: {{ .Values.namespace.name }}

spec:

  ports:

  - port: {{ .Values.service.port }}

    protocol: {{ .Values.service.protocol }}

    targetPort: {{ .Values.service.targetPort }}

  selector:

    app: {{ .Values.AppName }}

  type: {{ .Values.service.type }}
