apiVersion:

  long: apps/v1
  
  short: v1

AppName: techtrends

kind:

  fordeploy: Deployment
  
  fornamespace: Namespace 
  
  forservice: Service

namespace:

  name: sandbox

metadata:

  containers:

    image: richardvecsey/techtrends:latest
  
  name: techtrends

service:

  port: 4111

  targetPort: 3111

  protocol: TCP

  type: ClusterIP

image:

  repository: techtrends

  tag: latest

  pullPolicy: IfNotPresent

replicaCount: 1

resources:

  requests:

    memory: 64Mi

    cpu: 250m

  limits:

    memory: 128Mi

    cpu: 500m

containerPort: 3111

livenessProbe:

  path: /healthz

  port: 3111

  initialDelaySeconds: 30

  periodSeconds: 3

readinessProbe:

  path: /healthz

  port: 3111

  initialDelaySeconds: 30

  periodSeconds: 3
